# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b4c6d1cd8f6a13e7e2d52b9c8e4b52bebfcd92a9a2281d70c75549f489ff4979686032d80d2006257f48f1a42fb1cc137a6c57af37c46ee595b19b24278d825

test:
  secret_key_base: eb411eecde60017a3d8f1715c5f0b080b35275f926e9a389ea3d1c47c128c9bf5392299e336cb2ee5e1afba0cc7082a1ef3fb16826d282bbcb5fb1addc60b105

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
